### ISSUE TITLE
交易列表月份汇总计算错 

### ISSUE THREAD

**Issue by leenzhu** [mayswind/ezbookkeeping#13]
![image](https://user-images.githubusercontent.com/25599632/222878435-817e34f8-e2d1-49fd-9068-d280c9258512.png)
打开交易列表，选今年，之前月份统计汇总出错，刷新面页后可计算机正确。

**Comment by mayswind** [comment]
这不是bug，有加号的时候表示当月数据没有拉全。继续向后刷新就会显示完整数据。ezbookkeeping不是一次保证拉满一个月数据，而是一次拉够指定条数。
