### ISSUE TITLE
docker部署之后，数据库文件在哪里，如果我更新镜像并重启容器，数据是否会丢失

### ISSUE THREAD

**Issue by HelloMusician** [mayswind/ezbookkeeping#18]
docker部署之后，数据库文件在哪里，如果我更新镜像并重启容器，数据是否会丢失？

**Comment by mayswind** [comment]
如果是用sqlite的话，默认在容器内的 `/ezbookkeeping/data/ezbookkeeping.db`，具体可以参考 [conf.ini](https://github.com/mayswind/ezbookkeeping/blob/main/conf/ezbookkeeping.ini)。
sqlite仅建议验证和测试部署时使用，如果没有单独挂载卷的话，杀掉容器后肯定会丢失。如果正式使用，建议使用mysql或pg。

**Comment by HelloMusician** [comment]
> 如果是用sqlite的话，默认在容器内的 `/ezbookkeeping/data/ezbookkeeping.db`，具体可以参考 [conf.ini](https://github.com/mayswind/ezbookkeeping/blob/main/conf/ezbookkeeping.ini)。 sqlite仅建议验证和测试部署时使用，如果没有单独挂载卷的话，杀掉容器后肯定会丢失。如果正式使用，建议使用mysql或pg。

感谢，我就是没找到mysql的版本所以就用的sqlite，是直接在conf.ini里修改就生效了吗

**Comment by mayswind** [comment]
这里有简体中文详细的文档 http://ezbookkeeping.mayswind.net/zh_Hans/installation
