### ISSUE TITLE
如何设置ssl？

### ISSUE THREAD

**Issue by HelloMusician** [mayswind/ezbookkeeping#19]
我看ini文件里有个certfile 和cert-keyfile，需要只需要配置这个路径就行了吗
比如我映射的宿主机目录是/ezbookkeeping/conf，我把证书文件放这个目录下，那么ini里面的对应路径是否是这样？
/ezbookkeeping/conf/cert.crt
/ezbookkeeping/conf/cert-key.key

谢谢。

**Comment by mayswind** [comment]
配置说明有简体中文的文档，http://ezbookkeeping.mayswind.net/zh_Hans/configuration

**Comment by HelloMusician** [comment]
> 配置说明有简体中文的文档，http://ezbookkeeping.mayswind.net/zh_Hans/configuration

好的，谢谢
