### ISSUE TITLE
[Feature Request] 希望增加按标签过滤汇总功能

### ISSUE THREAD

**Issue by leenzhu** [mayswind/ezbookkeeping#20]
在使用过程中，我有时会给不同类别的支出打上相同的签，比如：

|类别|物品|标签|
|----|----|----|
|电器|冰箱|厨房|
|餐具|碗|厨房|
|食材|牛肉|厨房|

我想统计一下某年，或某个季度，我为`厨房`购买了哪些物品，总共支出了多少。

**Comment by mayswind** [comment]
今天的每日构建已经支持该功能，分类分析和趋势分析都支持筛选特定标签
