### ISSUE TITLE
Enhancement request: edit some basic CSS

### ISSUE THREAD

**Issue by arielsbecker** [mayswind/ezbookkeeping#24]
Hi! I'm pretty much satisfied with this project, and I'm using it on a daily basis without any issue so far. However, it would be cool if I was able to change some basic CSS, like the color used to show positive and negative values.

For example, I'm accustomed to use green for incomes, while I keep the red for anything that's a spending. Right now it's the other way around, and I didn't find any way to change it except re-compile the entire program after editing the assets.

**Comment by mayswind** [comment]
the latest daily build has supported this feature
