### ISSUE TITLE
Numpad input does not work

### ISSUE THREAD

**Issue by vigdail** [mayswind/ezbookkeeping#25]
Hello, after upgrading to `v0.5.0` it is impossible to enter transaction `amount` value using numpad keys. The same error occurs in the current online demo.

Other fields in transaction tab such as `description` and `tags` are working properly with numpad input

**Comment by mayswind** [comment]
this commit (https://github.com/mayswind/ezbookkeeping/commit/110179664190f0933de508e96fcd6c0a48de6f0b) has fixed this bug. you can try to use the latest daily build.

**Comment by vigdail** [comment]
Works fine, thank you
