### ISSUE TITLE
Feature Request | Credit Card Statement Date View and Payment Button

### ISSUE THREAD

**Issue by crazyvral** [mayswind/ezbookkeeping#26]
Expectations:
When viewing creditcards listed transaction will list only the transaction from statement date to the day before the next statement date.
Payment button shortcut inside creditcard accounts to initiate the recording of transfer for the payment.

Additional parameter need for credit cards Statement dates e.g every 8th, 20th and so on.

**Comment by mayswind** [comment]
the latest daily build has supported this feature

**Comment by schiinov** [comment]
Does the "Payment button shortcut inside creditcard accounts to initiate the recording of transfer for the payment"  added?
