### ISSUE TITLE
UX Enhancement | (Mobile) Clicking Date Should Pop-up Calendar-date-picker When Adding or Editing Transactions

### ISSUE THREAD

**Issue by crazyvral** [mayswind/ezbookkeeping#28]
UX Enhancement | (Mobile) Clicking Date Should Pop-up Calendar-date-picker When Adding or Editing Transactions

Expected behavior: Clicking/press the date the calendar-date picker should pop-up first not the time-wheels picker. Then clicking/press time should pop-up the time-wheels picker.

Current behavior: Clicking date or time show time-wheels picker.

**Comment by mayswind** [comment]
I think changing transaction time is more popular than changing time.

**Comment by crazyvral** [comment]
It could be split into 2 fields. One for the time and another for the date. So when clicking date calendar-date picker will show up, then when clicking time time-picker will show up.


BTW I'm starting to use your app so i may raise future issues and suggestions if i can think of any.

**Comment by mayswind** [comment]
Date and time should not be split into 2 fields. It would make users confused when split them. It's welcome to provide more useful suggestion about this issue.

**Comment by crazyvral** [comment]
On mobile date and time can be adjusted independently. Hence clicking the date should pop up calendar picker and clicking the time should pop up time picker.

similar to this below. 

![ezgif-5-c66f7a9470](https://github.com/user-attachments/assets/efef2d0f-cd5d-476f-932e-5ff8c4c4f883)

Anyway if this can't be done we can close the issue for now.

**Comment by mayswind** [comment]
in the latest build, the initial display mode of the date time sheet would depend on the clicked content. when you click the date, the date time sheet would display the date first.

**Comment by WLun001** [comment]
thanks for this!
