### ISSUE TITLE
Select currency when adding transaction

### ISSUE THREAD

**Issue by WLun001** [mayswind/ezbookkeeping#4]
Since it supports multiple currencies, but not able to select currency when adding transactions

**Comment by mayswind** [comment]
You can choose currency when you add an account. The currency of transaction in one account could be only one.

**Comment by WLun001** [comment]
I see. If I have the use case of multiple currency, means I have to create multiple accounts?

**Comment by mayswind** [comment]
yes

**Comment by WLun001** [comment]
thanks for the reply
